#!/bin/bash
# Secret Santa Django App - Get Started Script
# Copy-paste these commands to get up and running

echo "🎄 Secret Santa Django App - Getting Started 🎄"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Follow these steps to get your app running:"
echo ""
echo "STEP 1: Navigate to project directory"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo 'cd "/Users/ashr/Documents/MaProjects/Christmas Secret Santa"'
echo ""
echo ""
echo "STEP 2: Activate virtual environment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "source venv/bin/activate"
echo ""
echo "(You should see (venv) at start of your prompt)"
echo ""
echo ""
echo "STEP 3: Create superuser (admin account)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "python manage.py createsuperuser"
echo ""
echo "When prompted:"
echo "  - Username: admin (or your choice)"
echo "  - Email: admin@example.com (or your email)"
echo "  - Password: (enter a password)"
echo "  - Confirm password: (re-enter password)"
echo ""
echo ""
echo "STEP 4: Start development server"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "python manage.py runserver"
echo ""
echo "Output will show:"
echo "  Starting development server at http://127.0.0.1:8000/"
echo ""
echo ""
echo "STEP 5: Open in browser"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Admin Dashboard:        http://127.0.0.1:8000/"
echo "Django Admin:           http://127.0.0.1:8000/admin/"
echo "Participant Reveal:     http://127.0.0.1:8000/participant/"
echo ""
echo ""
echo "🎁 USAGE INSTRUCTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to admin dashboard (http://127.0.0.1:8000/)"
echo "2. Click 'Generate Secret Santa Draw' button"
echo "3. View tokens by clicking 'Show All Tokens'"
echo "4. Print tokens by clicking 'Print Tokens for Distribution'"
echo "5. Give each token to the corresponding person"
echo "6. Share participant page: http://127.0.0.1:8000/participant/"
echo "7. Participants enter their token to reveal recipient"
echo ""
echo ""
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "README.md           - Complete documentation"
echo "QUICKSTART.md       - Quick start guide"
echo "SETUP_COMPLETE.md   - Setup information"
echo "PROJECT_OVERVIEW.md - Technical overview"
echo ""
echo ""
echo "🔧 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Port 8000 already in use?"
echo "  python manage.py runserver 8080"
echo ""
echo "Can't find venv?"
echo "  cd 'Christmas Secret Santa'"
echo "  ls -la venv/ (check if venv exists)"
echo ""
echo "Database issues?"
echo "  rm db.sqlite3"
echo "  python manage.py migrate"
echo "  python manage.py populate_participants"
echo ""
echo ""
echo "✨ QUICK COPY-PASTE COMMANDS ✨"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Full setup (run these in sequence):"
echo 'cd "/Users/ashr/Documents/MaProjects/Christmas Secret Santa"'
echo "source venv/bin/activate"
echo "python manage.py createsuperuser"
echo "python manage.py runserver"
echo ""
echo ""
echo "🎉 All set! Server starting at http://127.0.0.1:8000/"
echo ""
echo "Happy Secret Santa! 🎄✨🎁"
